---

- name: Install default jdk
  apt:
    name: default-jdk
    state: present

- name: Get sample app artifact
  get_url:
    url: https://github.com/vinicyusmacedo/fatec-les/releases/download/servlet-exercicio-3/jogos.tar.gz
    dest: /tmp/jogos.tar.gz

- name: Untar artifact
  unarchive:
    src: /tmp/jogos.tar.gz
    dest: /opt/tomcat/webapps/
    owner: tomcat
    group: tomcat
