---

- name: Create tomcat group
  group:
    name: tomcat
    state: present

- name: Create tomcat user
  user:
    name: tomcat
    groups: tomcat

- name: Create tomcat directory
  file:
    path: /opt/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Install default jdk
  apt:
    name: default-jdk
    state: present

- name: Download tomcat
  get_url: 
    url: http://mirror.nbtelecom.com.br/apache/tomcat/tomcat-9/v9.0.20/bin/apache-tomcat-9.0.20.tar.gz
    dest: /tmp/apache-tomcat.tar.gz

- name: Untar tomcat
  unarchive:
    src: /tmp/apache-tomcat.tar.gz
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    extra_opts: [--strip-components=1]

- name: Copy tomcat.service
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
  notify: reload systemd

- name: Start tomcat.service
  systemd:
    name: tomcat.service
    state: started

- name: Check if tomcat is up
  shell: curl localhost:8080
