Vagrant.configure("2") do |config|
  config.vm.define "elk" do |elk|
    elk.vm.box = "ubuntu/bionic64"
    elk.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "provisioning/elk.yml"
    end
  end
end
