---

- name: Install netplan
  apt:
    name: netplan
    state: present

- name: Create netplan dir
  file:
    name: /etc/netplan
    state: directory

- name: Copy network config
  template:
    src: templates/50-vagrant.yaml.j2
    dest: /etc/netplan/50-vagrant.yaml
    owner: root
    group: root
  notify: Apply netplan
