---

- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    - gateway_address: 10.49.0.1
    - internal_iface: enp0s8
    - is_gateway: false
  roles:
    - netplan
    - common
    - ssh-access
    - tomcat
    - sample-java-app

